//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.IMS.MailService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENETCare.IMS.MailService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        *
        ///        {
        ///            margin: 0;
        ///            padding: 0;
        ///
        ///            font-family: &apos;Arial Narrow&apos;, Arial, sans-serif;
        ///        }
        ///
        ///        h1, h2, h3
        ///        {
        ///            padding: 10px;
        ///        }
        ///
        ///        .wrapperDiv
        ///        {
        ///            width: 50%;
        ///            height: 100vh;
        ///            margin: 0 auto;
        ///            padding: 60px;
        ///
        ///            background: #F7F7F7;
        ///        }
        ///
        ///        #messagePara
        ///        {
        ///            width: 97%;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailBodyFormat {
            get {
                return ResourceManager.GetString("EmailBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An intervention that you proposed has been &lt;b&gt;{0}&lt;/b&gt;.&lt;br/&gt;
        ///Please review the details of the intervention.&lt;br/&gt;&lt;br/&gt;
        ///
        ///&lt;b&gt;Type: &lt;/b&gt;{1}&lt;br/&gt;
        ///&lt;b&gt;Client: &lt;/b&gt;{2}&lt;br/&gt;.
        /// </summary>
        internal static string InterventionStateChangeMessageFormat {
            get {
                return ResourceManager.GetString("InterventionStateChangeMessageFormat", resourceCulture);
            }
        }
    }
}
