// <auto-generated />
namespace ENETCare.IMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserDistrictColName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDistrictColName));
        
        string IMigrationMetadata.Id
        {
            get { return "201605300846428_UserDistrictColName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
